"""Add username column (nullable)

Revision ID: 2a49e98f9f73
Revises: 453e1f4480ec
Create Date: 2025-04-18 22:42:46.849015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a49e98f9f73'
down_revision = '453e1f4480ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_chat_message', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
