"""Add ProductImage table

Revision ID: 453e1f4480ec
Revises: 881c93a34621
Create Date: 2025-04-18 19:16:06.997821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453e1f4480ec'
down_revision = '881c93a34621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    # ### end Alembic commands ###
